package com.example.project01.entity;

import com.baomidou.mybatisplus.annotation.FieldFill;
import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import lombok.Data;

import java.time.LocalDateTime;

/**
 * Notification generated by an order event and delivered to one recipient.
 */
@Data
@TableName("order_notification")
public class OrderNotification {

    @TableId(type = IdType.AUTO)
    private Long id;

    private Long orderId;

    private String eventType;

    private Long recipientId;

    private String recipientRole;

    private String title;

    private String content;

    @TableField("is_read")
    private Boolean readFlag;

    @TableField(fill = FieldFill.INSERT)
    private LocalDateTime createTime;
}
