const MESSAGE_MAP = {
  success: '操作成功',
  'bad request': '请求参数错误',
  unauthorized: '登录状态已失效，请重新登录',
  forbidden: '没有权限执行此操作',
  'resource not found': '请求的资源不存在',
  'internal server error': '服务器内部错误，请稍后重试',
  'too many requests': '操作过于频繁，请稍后再试',
  'user does not exist': '用户不存在',
  'product does not exist': '商品不存在',
  'insufficient stock': '商品库存不足',
  'category has children or products, cannot delete': '分类下存在子分类或商品，无法删除',
  'cart item does not exist': '购物车商品不存在',
  'username or password is wrong': '用户名或密码错误',
  'username already exists': '用户名已存在',
  'product is not owned by current seller': '该商品不属于当前卖家',
  'invalid role': '用户角色无效',
  'only completed orders can be reviewed': '确认收货后才能发布评价',
  'this order item has already been reviewed': '该订单商品已经评价过了',
  'refunded product cannot be reviewed': '已退款商品不能评价',
  'cart is empty': '购物车为空，无法创建订单',
  'only unpaid order can be canceled': '只有待付款订单可以取消',
  'order status is invalid': '当前订单状态不允许执行该操作',
  'only paid order can be shipped': '只有已付款订单可以发货',
  'only shipped order can be confirmed': '只有已发货订单可以确认收货',
  'order status cannot be force canceled': '当前订单状态不能强制关单',
  'refund is available before completion or within 7 days': '发货后或确认收货后七天内可以申请退款',
  'return request already exists': '该订单商品已经提交过退款申请',
  'only applied returns can be canceled': '只有待处理的退款申请可以撤销',
  'only applied returns can be approved': '只有待处理的退款申请可以同意',
  'only applied returns can be rejected': '只有待处理的退款申请可以拒绝',
  'category name already exists': '分类名称已存在',
  'file must not be empty': '上传文件不能为空',
  'only jpg/jpeg/png/gif/webp images are allowed': '仅支持 JPG、JPEG、PNG、GIF、WEBP 图片',
  'missing bearer token': '缺少登录令牌，请重新登录',
  'invalid token': '登录状态已失效，请重新登录',
  'java api error': 'Java 服务调用失败',
  'Agent call failed.': 'AI 助手调用失败',
  'I could not generate an answer from the available facts.': '暂时无法根据现有信息生成回答',
  'Sorry, need more steps to process this request.': '当前问题较复杂，请换一种更简洁的问法后重试',
  'unknown error': '未知错误',
  'Network Error': '网络连接失败，请检查服务是否正常运行',
  'Order created': '订单已创建',
  'Payment successful': '支付成功',
  'New paid order': '新订单已付款',
  'username must not be blank': '用户名不能为空',
  'username length must be 2-20': '用户名长度必须为 2-20 个字符',
  'password must not be blank': '密码不能为空',
  'password length must be 6-100': '密码长度必须为 6-100 个字符',
  'email format is invalid': '邮箱格式不正确',
  'reply content must not be blank': '回复内容不能为空',
  'reply content cannot exceed 500 chars': '回复内容不能超过 500 个字符',
  'order item id must not be null': '订单商品不能为空',
  'rating must not be null': '评分不能为空',
  'rating must be at least 1': '评分不能低于 1 分',
  'rating must be at most 5': '评分不能高于 5 分',
  'review content cannot exceed 500 chars': '评价内容不能超过 500 个字符',
  'category name must not be blank': '分类名称不能为空',
  'category name length must be 1-50': '分类名称长度必须为 1-50 个字符',
  'parent id must not be null': '父分类不能为空',
  'parent id cannot be negative': '父分类编号不能为负数',
  'sort order must not be null': '排序值不能为空',
  'sort order cannot be negative': '排序值不能为负数',
  'category status must not be null': '分类状态不能为空',
  'seller id must not be null': '卖家不能为空',
  'product name must not be blank': '商品名称不能为空',
  'product name length must be 1-100': '商品名称长度必须为 1-100 个字符',
  'product description cannot exceed 500 chars': '商品描述不能超过 500 个字符',
  'product price must not be null': '商品价格不能为空',
  'product price must be greater than 0': '商品价格必须大于 0',
  'product stock must not be null': '商品库存不能为空',
  'product stock cannot be negative': '商品库存不能为负数',
  'category id must not be null': '商品分类不能为空',
  'product status must not be null': '商品状态不能为空',
  'handle note cannot exceed 500 chars': '处理说明不能超过 500 个字符',
  'old password must not be blank': '原密码不能为空',
  'new password must not be blank': '新密码不能为空',
  'refresh token must not be blank': '刷新令牌不能为空',
  'quantity must not be null': '商品数量不能为空',
  'quantity must be at least 1': '商品数量不能少于 1 件',
  'product id must not be null': '商品不能为空',
  'role must not be null': '用户角色不能为空',
  'nickname length cannot exceed 50': '昵称不能超过 50 个字符',
  'shop name length cannot exceed 100': '店铺名称不能超过 100 个字符',
  'phone length cannot exceed 20': '手机号不能超过 20 个字符',
  'address length cannot exceed 255': '地址不能超过 255 个字符',
  'idempotency key must not be blank': '订单幂等标识不能为空',
  'idempotency key length cannot exceed 64': '订单幂等标识不能超过 64 个字符',
  'receiver name must not be blank': '收货人不能为空',
  'receiver name length cannot exceed 50': '收货人姓名不能超过 50 个字符',
  'receiver phone must not be blank': '收货手机号不能为空',
  'receiver phone length cannot exceed 20': '收货手机号不能超过 20 个字符',
  'receiver address must not be blank': '收货地址不能为空',
  'receiver address length cannot exceed 200': '收货地址不能超过 200 个字符',
  'buyer id must not be null': '买家不能为空',
  'order no must not be blank': '订单号不能为空',
  'order no length cannot exceed 50': '订单号不能超过 50 个字符',
  'total amount must not be null': '订单金额不能为空',
  'order status must not be null': '订单状态不能为空',
  'return reason must not be blank': '退款原因不能为空',
  'return reason cannot exceed 500 chars': '退款原因不能超过 500 个字符'
}

const MESSAGE_PATTERNS = [
  [/^Request failed with status code \d+$/, '请求失败，请稍后重试'],
  [/^timeout of \d+ms exceeded$/, '请求超时，请稍后重试'],
  [/^Your order (.+) has been created\.$/, '您的订单 $1 已创建。'],
  [/^Your order (.+) has been paid\.$/, '您的订单 $1 已支付。'],
  [/^Order (.+) has been paid\.$/, '订单 $1 已付款。'],
  [/^账号或密码错误$/, '账号或密码错误']
]

export function localizeMessage(value) {
  const text = String(value ?? '').trim()
  if (!text) return ''
  if (MESSAGE_MAP[text]) return MESSAGE_MAP[text]
  for (const [pattern, replacement] of MESSAGE_PATTERNS) {
    if (pattern.test(text)) return text.replace(pattern, replacement)
  }
  return text
}
